#!/usr/bin/env node

/**
 * 自动化工作流汉化脚本
 * 从报告文件中读取需要汉化的工作流，批量添加到中文翻译文件中
 */

const fs = require('fs');
const path = require('path');

// 配置路径
const REPORT_JSON_PATH = path.join(__dirname, '../reports/workflow_i18n_report.json');
const TRANSLATION_FILE_PATH = path.join(__dirname, '../static/locales/zh/translation.json');

// 每批处理的工作流数量
const BATCH_SIZE = 200;

// 翻译函数 - 简单的规则翻译
function translateTitle(title) {
  // 简单的翻译规则映射
  const translations = {
    'Workflow': '工作流',
    'Trigger': '触发器',
    'Automation': '自动化',
    'Create': '创建',
    'Update': '更新',
    'Delete': '删除',
    'Send': '发送',
    'Receive': '接收',
    'Automated workflow:': '自动化工作流：',
    'Production Workflow': '生产环境工作流',
    'Production-ready workflow:': '生产就绪工作流：',
    'Unnamed Workflow': '未命名工作流',
    'Manual': '手动',
    'Scheduled': '计划任务',
    'Webhook': '网络钩子',
    'Agent': '智能代理',
    'Email': '邮件',
    'Slack': 'Slack',
    'Telegram': 'Telegram',
    'Discord': 'Discord',
    'Gmail': 'Gmail',
    'Google Sheets': 'Google Sheets',
    'Google Drive': 'Google Drive',
    'Calendar': '日历',
    'Data': '数据',
    'Process': '处理',
    'API': 'API',
    'HTTP': 'HTTP',
    'JSON': 'JSON',
    'CSV': 'CSV',
    'XML': 'XML',
    'PDF': 'PDF',
    'Excel': 'Excel',
    'Word': 'Word',
    'PowerPoint': 'PowerPoint',
    'Image': '图片',
    'Video': '视频',
    'Audio': '音频',
    'Text': '文本',
    'File': '文件',
    'Folder': '文件夹',
    'Database': '数据库',
    'Table': '表格',
    'Record': '记录',
    'Field': '字段',
    'Query': '查询',
    'Report': '报告',
    'Dashboard': '仪表板',
    'Chart': '图表',
    'Graph': '图形',
    'Analytics': '分析',
    'Statistics': '统计',
    'Log': '日志',
    'Error': '错误',
    'Warning': '警告',
    'Info': '信息',
    'Success': '成功',
    'Failed': '失败',
    'Pending': '待处理',
    'Completed': '已完成',
    'Running': '运行中',
    'Stopped': '已停止',
    'Paused': '已暂停',
    'Active': '活跃',
    'Inactive': '非活跃',
    'Enabled': '已启用',
    'Disabled': '已禁用',
    'Online': '在线',
    'Offline': '离线',
    'Connected': '已连接',
    'Disconnected': '已断开',
    'Login': '登录',
    'Logout': '登出',
    'Register': '注册',
    'User': '用户',
    'Account': '账户',
    'Profile': '个人资料',
    'Settings': '设置',
    'Configuration': '配置',
    'Options': '选项',
    'Preferences': '首选项',
    'Language': '语言',
    'Theme': '主题',
    'Color': '颜色',
    'Style': '样式',
    'Layout': '布局',
    'Design': '设计',
    'Template': '模板',
    'Format': '格式',
    'Size': '大小',
    'Length': '长度',
    'Width': '宽度',
    'Height': '高度',
    'Weight': '重量',
    'Price': '价格',
    'Cost': '成本',
    'Budget': '预算',
    'Amount': '金额',
    'Quantity': '数量',
    'Count': '计数',
    'Total': '总计',
    'Sum': '总和',
    'Average': '平均值',
    'Minimum': '最小值',
    'Maximum': '最大值',
    'Range': '范围',
    'Filter': '筛选',
    'Sort': '排序',
    'Search': '搜索',
    'Find': '查找',
    'Replace': '替换',
    'Copy': '复制',
    'Paste': '粘贴',
    'Cut': '剪切',
    'Undo': '撤销',
    'Redo': '重做',
    'Save': '保存',
    'Load': '加载',
    'Import': '导入',
    'Export': '导出',
    'Download': '下载',
    'Upload': '上传',
    'Sync': '同步',
    'Backup': '备份',
    'Restore': '恢复',
    'Archive': '归档',
    'Delete': '删除',
    'Remove': '移除',
    'Add': '添加',
    'Edit': '编辑',
    'Modify': '修改',
    'Change': '更改',
    'Update': '更新',
    'Refresh': '刷新',
    'Reload': '重新加载',
    'Reset': '重置',
    'Clear': '清除',
    'Clean': '清理',
    'Optimize': '优化',
    'Improve': '改进',
    'Enhance': '增强',
    'Upgrade': '升级',
    'Install': '安装',
    'Uninstall': '卸载',
    'Configure': '配置',
    'Customize': '自定义',
    'Personalize': '个性化',
    'Share': '分享',
    'Publish': '发布',
    'Subscribe': '订阅',
    'Follow': '关注',
    'Like': '喜欢',
    'Comment': '评论',
    'Review': '评论',
    'Rate': '评分',
    'Feedback': '反馈',
    'Contact': '联系',
    'Support': '支持',
    'Help': '帮助',
    'Documentation': '文档',
    'Tutorial': '教程',
    'Guide': '指南',
    'FAQ': '常见问题',
    'About': '关于',
    'Terms': '条款',
    'Privacy': '隐私',
    'Security': '安全',
    'Policy': '政策',
    'Agreement': '协议',
    'License': '许可证',
    'Copyright': '版权',
    'Trademark': '商标',
    'Patent': '专利',
    'Version': '版本',
    'Release': '发布',
    'Update': '更新',
    'Patch': '补丁',
    'Fix': '修复',
    'Bug': '错误',
    'Issue': '问题',
    'Request': '请求',
    'Feature': '功能',
    'Enhancement': '增强',
    'Improvement': '改进',
    'Suggestion': '建议',
    'Idea': '想法',
    'Proposal': '提案',
    'Plan': '计划',
    'Schedule': '计划',
    'Timeline': '时间线',
    'Deadline': '截止日期',
    'Milestone': '里程碑',
    'Goal': '目标',
    'Objective': '目标',
    'Purpose': '目的',
    'Mission': '使命',
    'Vision': '愿景',
    'Strategy': '策略',
    'Tactic': '战术',
    'Method': '方法',
    'Approach': '方法',
    'Technique': '技术',
    'Tool': '工具',
    'Software': '软件',
    'Application': '应用程序',
    'Service': '服务',
    'Platform': '平台',
    'System': '系统',
    'Network': '网络',
    'Server': '服务器',
    'Client': '客户端',
    'Browser': '浏览器',
    'Website': '网站',
    'Webpage': '网页',
    'URL': '网址',
    'Link': '链接',
    'Button': '按钮',
    'Menu': '菜单',
    'Navigation': '导航',
    'Header': '页眉',
    'Footer': '页脚',
    'Sidebar': '侧边栏',
    'Content': '内容',
    'Body': '正文',
    'Title': '标题',
    'Subtitle': '副标题',
    'Heading': '标题',
    'Paragraph': '段落',
    'List': '列表',
    'Item': '项目',
    'Row': '行',
    'Column': '列',
    'Cell': '单元格',
    'Table': '表格',
    'Form': '表单',
    'Input': '输入',
    'Output': '输出',
    'Field': '字段',
    'Label': '标签',
    'Value': '值',
    'Text': '文本',
    'Number': '数字',
    'Date': '日期',
    'Time': '时间',
    'Email': '邮箱',
    'Phone': '电话',
    'Address': '地址',
    'Location': '位置',
    'Map': '地图',
    'Image': '图片',
    'Photo': '照片',
    'Picture': '图片',
    'Video': '视频',
    'Audio': '音频',
    'Music': '音乐',
    'Sound': '声音',
    'Voice': '语音',
    'Speech': '语音',
    'Language': '语言',
    'Translation': '翻译',
    'Locale': '地区',
    'Region': '区域',
    'Country': '国家',
    'City': '城市',
    'State': '州',
    'Province': '省',
    'Zip': '邮编',
    'Postal': '邮政',
    'Code': '代码',
    'Script': '脚本',
    'Program': '程序',
    'Function': '函数',
    'Method': '方法',
    'Class': '类',
    'Object': '对象',
    'Variable': '变量',
    'Constant': '常量',
    'Parameter': '参数',
    'Argument': '参数',
    'Return': '返回',
    'Result': '结果',
    'Output': '输出',
    'Input': '输入',
    'Process': '处理',
    'Execute': '执行',
    'Run': '运行',
    'Start': '开始',
    'Stop': '停止',
    'Pause': '暂停',
    'Resume': '继续',
    'Restart': '重新启动',
    'Shutdown': '关闭',
    'Exit': '退出',
    'Quit': '退出',
    'Cancel': '取消',
    'Abort': '中止',
    'Skip': '跳过',
    'Next': '下一个',
    'Previous': '上一个',
    'First': '第一个',
    'Last': '最后一个',
    'Current': '当前',
    'Selected': '已选择',
    'Active': '活跃',
    'Inactive': '非活跃',
    'Available': '可用',
    'Unavailable': '不可用',
    'Online': '在线',
    'Offline': '离线',
    'Connected': '已连接',
    'Disconnected': '已断开',
    'Ready': '就绪',
    'Busy': '忙碌',
    'Loading': '加载中',
    'Processing': '处理中',
    'Completed': '已完成',
    'Failed': '失败',
    'Error': '错误',
    'Warning': '警告',
    'Info': '信息',
    'Success': '成功',
    'Message': '消息',
    'Notification': '通知',
    'Alert': '提醒',
    'Reminder': '提醒',
    'Note': '备注',
    'Comment': '评论',
    'Description': '描述',
    'Summary': '摘要',
    'Overview': '概览',
    'Details': '详情',
    'Information': '信息',
    'Data': '数据',
    'Content': '内容',
    'File': '文件',
    'Document': '文档',
    'Image': '图片',
    'Video': '视频',
    'Audio': '音频',
    'Media': '媒体',
    'Resource': '资源',
    'Asset': '资产',
    'Library': '库',
    'Collection': '集合',
    'Set': '集合',
    'Group': '组',
    'Category': '分类',
    'Type': '类型',
    'Kind': '种类',
    'Sort': '种类',
    'Style': '样式',
    'Format': '格式',
    'Layout': '布局',
    'Design': '设计',
    'Theme': '主题',
    'Color': '颜色',
    'Size': '大小',
    'Shape': '形状',
    'Position': '位置',
    'Location': '位置',
    'Direction': '方向',
    'Alignment': '对齐',
    'Spacing': '间距',
    'Margin': '边距',
    'Padding': '内边距',
    'Border': '边框',
    'Background': '背景',
    'Foreground': '前景',
    'Text': '文本',
    'Font': '字体',
    'Size': '大小',
    'Weight': '字重',
    'Style': '样式',
    'Decoration': '装饰',
    'Transform': '转换',
    'Animation': '动画',
    'Transition': '过渡',
    'Effect': '效果',
    'Filter': '滤镜',
    'Shadow': '阴影',
    'Gradient': '渐变',
    'Pattern': '图案',
    'Texture': '纹理',
    'Opacity': '不透明度',
    'Transparency': '透明度',
    'Visibility': '可见性',
    'Display': '显示',
    'Hidden': '隐藏',
    'Show': '显示',
    'Hide': '隐藏',
    'Expand': '展开',
    'Collapse': '折叠',
    'Open': '打开',
    'Close': '关闭',
    'Minimize': '最小化',
    'Maximize': '最大化',
    'Restore': '恢复',
    'Move': '移动',
    'Resize': '调整大小',
    'Drag': '拖拽',
    'Drop': '放置',
    'Scroll': '滚动',
    'Zoom': '缩放',
    'Pan': '平移',
    'Rotate': '旋转',
    'Flip': '翻转',
    'Mirror': '镜像',
    'Crop': '裁剪',
    'Scale': '缩放',
    'Skew': '倾斜',
    'Distort': '扭曲',
    'Warp': '弯曲',
    'Perspective': '透视',
    'Transform': '变换',
    'Animate': '动画',
    'Transition': '过渡',
    'Effect': '效果',
    'Filter': '滤镜',
    'Adjust': '调整',
    'Enhance': '增强',
    'Correct': '校正',
    'Repair': '修复',
    'Fix': '修复',
    'Improve': '改进',
    'Optimize': '优化',
    'Clean': '清理',
    'Organize': '组织',
    'Arrange': '排列',
    'Sort': '排序',
    'Group': '分组',
    'Ungroup': '取消分组',
    'Merge': '合并',
    'Split': '拆分',
    'Combine': '组合',
    'Separate': '分离',
    'Join': '连接',
    'Connect': '连接',
    'Disconnect': '断开连接',
    'Link': '链接',
    'Unlink': '取消链接',
    'Attach': '附加',
    'Detach': '分离',
    'Add': '添加',
    'Remove': '移除',
    'Insert': '插入',
    'Delete': '删除',
    'Edit': '编辑',
    'Modify': '修改',
    'Change': '更改',
    'Update': '更新',
    'Replace': '替换',
    'Exchange': '交换',
    'Swap': '交换',
    'Switch': '切换',
    'Toggle': '切换',
    'Enable': '启用',
    'Disable': '禁用',
    'Activate': '激活',
    'Deactivate': '停用',
    'Turn on': '开启',
    'Turn off': '关闭',
    'Power on': '开机',
    'Power off': '关机',
    'Start': '开始',
    'Begin': '开始',
    'Launch': '启动',
    'Initialize': '初始化',
    'Setup': '设置',
    'Configure': '配置',
    'Customize': '自定义',
    'Personalize': '个性化',
    'Adapt': '适应',
    'Adjust': '调整',
    'Tune': '调整',
    'Calibrate': '校准',
    'Test': '测试',
    'Check': '检查',
    'Verify': '验证',
    'Validate': '验证',
    'Confirm': '确认',
    'Approve': '批准',
    'Reject': '拒绝',
    'Accept': '接受',
    'Decline': '拒绝',
    'Agree': '同意',
    'Disagree': '不同意',
    'Allow': '允许',
    'Permit': '允许',
    'Forbid': '禁止',
    'Block': '阻止',
    'Prevent': '防止',
    'Avoid': '避免',
    'Stop': '停止',
    'Halt': '停止',
    'Pause': '暂停',
    'Continue': '继续',
    'Resume': '继续',
    'Proceed': '继续',
    'Advance': '前进',
    'Progress': '进展',
    'Complete': '完成',
    'Finish': '完成',
    'End': '结束',
    'Terminate': '终止',
    'Close': '关闭',
    'Exit': '退出',
    'Leave': '离开',
    'Quit': '退出',
    'Retire': '退出',
    'Withdraw': '撤回',
    'Cancel': '取消',
    'Abort': '中止',
    'Stop': '停止',
    'Halt': '停止',
    'Cease': '停止',
    'Suspend': '暂停',
    'Defer': '推迟',
    'Delay': '延迟',
    'Postpone': '推迟',
    'Schedule': '计划',
    'Plan': '计划',
    'Arrange': '安排',
    'Organize': '组织',
    'Coordinate': '协调',
    'Manage': '管理',
    'Control': '控制',
    'Supervise': '监督',
    'Monitor': '监控',
    'Track': '跟踪',
    'Follow': '跟随',
    'Observe': '观察',
    'Watch': '观看',
    'View': '查看',
    'See': '看见',
    'Look': '看',
    'Display': '显示',
    'Show': '显示',
    'Present': '呈现',
    'Demonstrate': '演示',
    'Explain': '解释',
    'Describe': '描述',
    'Illustrate': '说明',
    'Clarify': '阐明',
    'Define': '定义',
    'Specify': '指定',
    'Detail': '详情',
    'List': '列表',
    'Enumerate': '列举',
    'Mention': '提及',
    'Reference': '引用',
    'Cite': '引用',
    'Quote': '引用',
    'Paraphrase': '意译',
    'Summarize': '总结',
    'Outline': '概述',
    'Summarize': '总结',
    'Recap': ' recap',
    'Review': '审查',
    'Analyze': '分析',
    'Examine': '检查',
    'Inspect': '检查',
    'Investigate': '调查',
    'Research': '研究',
    'Study': '学习',
    'Learn': '学习',
    'Discover': '发现',
    'Find': '查找',
    'Search': '搜索',
    'Explore': '探索',
    'Browse': '浏览',
    'Navigate': '导航',
    'Surf': '浏览',
    'Scan': '扫描',
    'Filter': '筛选',
    'Sort': '排序',
    'Order': '排序',
    'Rank': '排名',
    'Rate': '评级',
    'Score': '得分',
    'Grade': '等级',
    'Level': '级别',
    'Degree': '程度',
    'Extent': '程度',
    'Scope': '范围',
    'Range': '范围',
    'Limit': '限制',
    'Boundary': '边界',
    'Border': '边框',
    'Edge': '边缘',
    'Margin': '边距',
    'Space': '空间',
    'Area': '区域',
    'Zone': '区域',
    'Region': '区域',
    'Territory': '领域',
    'Domain': '域',
    'Field': '字段',
    'Category': '分类',
    'Class': '类',
    'Group': '组',
    'Set': '集合',
    'Collection': '集合',
    'Series': '系列',
    'Sequence': '序列',
    'Order': '顺序',
    'Pattern': '模式',
    'Structure': '结构',
    'Framework': '框架',
    'System': '系统',
    'Model': '模型',
    'Template': '模板',
    'Format': '格式',
    'Layout': '布局',
    'Design': '设计',
    'Scheme': '方案',
    'Plan': '计划',
    'Strategy': '策略',
    'Method': '方法',
    'Approach': '方法',
    'Technique': '技术',
    'Procedure': '程序',
    'Process': '过程',
    'Workflow': '工作流',
    'Pipeline': '管道',
    'Channel': '频道',
    'Path': '路径',
    'Route': '路线',
    'Way': '方式',
    'Means': '手段',
    'Tool': '工具',
    'Instrument': '工具',
    'Equipment': '设备',
    'Device': '设备',
    'Machine': '机器',
    'Hardware': '硬件',
    'Software': '软件',
    'Program': '程序',
    'Application': '应用',
    'Service': '服务',
    'Platform': '平台',
    'Environment': '环境',
    'Infrastructure': '基础设施',
    'Architecture': '架构',
    'Blueprint': '蓝图',
    'Schema': '模式',
    'Specification': '规范',
    'Standard': '标准',
    'Protocol': '协议',
    'Interface': '接口',
    'API': 'API',
    'Library': '库',
    'Package': '包',
    'Module': '模块',
    'Component': '组件',
    'Element': '元素',
    'Part': '部分',
    'Piece': '片段',
    'Section': '部分',
    'Chapter': '章节',
    'Page': '页面',
    'Document': '文档',
    'File': '文件',
    'Folder': '文件夹',
    'Directory': '目录',
    'Path': '路径',
    'Location': '位置',
    'Address': '地址',
    'URL': '网址',
    'Link': '链接',
    'Connection': '连接',
    'Network': '网络',
    'Internet': '互联网',
    'Web': '网络',
    'Site': '站点',
    'Portal': '门户',
    'Hub': '中心',
    'Center': '中心',
    'Core': '核心',
    'Main': '主要',
    'Primary': '主要',
    'Secondary': '次要',
    'Tertiary': '第三',
    'Additional': '额外',
    'Extra': '额外',
    'Optional': '可选',
    'Required': '必需',
    'Mandatory': '强制',
    'Essential': '必要',
    'Important': '重要',
    'Critical': '关键',
    'Urgent': '紧急',
    'Priority': '优先级',
    'High': '高',
    'Medium': '中',
    'Low': '低',
    'Normal': '正常',
    'Regular': '常规',
    'Standard': '标准',
    'Basic': '基本',
    'Simple': '简单',
    'Complex': '复杂',
    'Advanced': '高级',
    'Expert': '专家',
    'Professional': '专业',
    'Enterprise': '企业',
    'Business': '业务',
    'Commercial': '商业',
    'Personal': '个人',
    'Private': '私有',
    'Public': '公共',
    'Global': '全球',
    'Local': '本地',
    'Regional': '区域',
    'National': '国家',
    'International': '国际',
    'Universal': '通用',
    'Common': '常见',
    'Rare': '罕见',
    'Unique': '独特',
    'Special': '特殊',
    'Custom': '自定义',
    'Tailored': '定制',
    'Personalized': '个性化',
    'Individual': '个人',
    'Specific': '特定',
    'General': '通用',
    'Generic': '通用',
    'Abstract': '抽象',
    'Concrete': '具体',
    'Virtual': '虚拟',
    'Physical': '物理',
    'Digital': '数字',
    'Electronic': '电子',
    'Manual': '手动',
    'Automatic': '自动',
    'Semi-automatic': '半自动',
    'Interactive': '交互式',
    'Reactive': '反应式',
    'Proactive': '主动',
    'Real-time': '实时',
    'Live': '实时',
    'Offline': '离线',
    'Online': '在线',
    'Connected': '已连接',
    'Disconnected': '已断开',
    'Available': '可用',
    'Unavailable': '不可用',
    'Ready': '就绪',
    'Busy': '忙碌',
    'Idle': '空闲',
    'Active': '活跃',
    'Inactive': '非活跃',
    'Enabled': '已启用',
    'Disabled': '已禁用',
    'Locked': '已锁定',
    'Unlocked': '已解锁',
    'Secured': '已保护',
    'Unsecured': '未保护',
    'Encrypted': '已加密',
    'Decrypted': '已解密',
    'Protected': '受保护',
    'Unprotected': '未保护',
    'Safe': '安全',
    'Unsafe': '不安全',
    'Secure': '安全',
    'Insecure': '不安全',
    'Trusted': '受信任',
    'Untrusted': '不受信任',
    'Verified': '已验证',
    'Unverified': '未验证',
    'Authenticated': '已认证',
    'Unauthenticated': '未认证',
    'Authorized': '已授权',
    'Unauthorized': '未授权',
    'Permitted': '已允许',
    'Forbidden': '禁止',
    'Allowed': '已允许',
    'Denied': '已拒绝',
    'Granted': '已授予',
    'Revoked': '已撤销',
    'Expired': '已过期',
    'Valid': '有效',
    'Invalid': '无效',
    'Correct': '正确',
    'Incorrect': '不正确',
    'True': '真',
    'False': '假',
    'Yes': '是',
    'No': '否',
    'On': '开',
    'Off': '关',
    'Up': '上',
    'Down': '下',
    'Left': '左',
    'Right': '右',
    'Forward': '前进',
    'Backward': '后退',
    'Next': '下一个',
    'Previous': '上一个',
    'First': '第一个',
    'Last': '最后一个',
    'Begin': '开始',
    'End': '结束',
    'Start': '开始',
    'Stop': '停止',
    'Top': '顶部',
    'Bottom': '底部',
    'Header': '页眉',
    'Footer': '页脚',
    'Sidebar': '侧边栏',
    'Content': '内容',
    'Main': '主要',
    'Primary': '主要',
    'Secondary': '次要',
    'Tertiary': '第三',
    'Navigation': '导航',
    'Menu': '菜单',
    'Toolbar': '工具栏',
    'Status bar': '状态栏',
    'Title bar': '标题栏',
    'Window': '窗口',
    'Dialog': '对话框',
    'Modal': '模态',
    'Popup': '弹出',
    'Dropdown': '下拉',
    'List': '列表',
    'Grid': '网格',
    'Table': '表格',
    'Form': '表单',
    'Input': '输入',
    'Output': '输出',
    'Button': '按钮',
    'Link': '链接',
    'Text': '文本',
    'Label': '标签',
    'Image': '图片',
    'Icon': '图标',
    'Avatar': '头像',
    'Profile': '个人资料',
    'User': '用户',
    'Account': '账户',
    'Settings': '设置',
    'Preferences': '首选项',
    'Configuration': '配置',
    'Options': '选项',
    'Properties': '属性',
    'Details': '详情',
    'Information': '信息',
    'Description': '描述',
    'Summary': '摘要',
    'Overview': '概览',
    'Introduction': '介绍',
    'Welcome': '欢迎',
    'Home': '首页',
    'Dashboard': '仪表板',
    'Main page': '主页',
    'Landing page': '落地页',
    'Search': '搜索',
    'Filter': '筛选',
    'Sort': '排序',
    'Pagination': '分页',
    'Results': '结果',
    'Items': '项目',
    'Records': '记录',
    'Entries': '条目',
    'Data': '数据',
    'Content': '内容',
    'Files': '文件',
    'Documents': '文档',
    'Images': '图片',
    'Videos': '视频',
    'Audio': '音频',
    'Media': '媒体',
    'Resources': '资源',
    'Downloads': '下载',
    'Uploads': '上传',
    'Imports': '导入',
    'Exports': '导出',
    'Backups': '备份',
    'Archives': '归档',
    'Logs': '日志',
    'Reports': '报告',
    'Statistics': '统计',
    'Analytics': '分析',
    'Metrics': '指标',
    'Performance': '性能',
    'Monitoring': '监控',
    'Alerts': '警报',
    'Notifications': '通知',
    'Messages': '消息',
    'Emails': '邮件',
    'SMS': '短信',
    'Calls': '电话',
    'Meetings': '会议',
    'Events': '事件',
    'Tasks': '任务',
    'Projects': '项目',
    'Workflows': '工作流',
    'Processes': '过程',
    'Procedures': '程序',
    'Policies': '政策',
    'Rules': '规则',
    'Regulations': '法规',
    'Guidelines': '指导方针',
    'Instructions': '说明',
    'Documentation': '文档',
    'Help': '帮助',
    'Support': '支持',
    'FAQ': '常见问题',
    'Tutorial': '教程',
    'Guide': '指南',
    'Manual': '手册',
    'Reference': '参考',
    'Glossary': '术语表',
    'Index': '索引',
    'Appendix': '附录',
    'Bibliography': '参考文献',
    'Credits': '致谢',
    'License': '许可证',
    'Terms': '条款',
    'Conditions': '条件',
    'Privacy': '隐私',
    'Security': '安全',
    'Legal': '法律',
    'Contact': '联系',
    'About': '关于',
    'Team': '团队',
    'Company': '公司',
    'Organization': '组织',
    'Department': '部门',
    'Division': '部门',
    'Unit': '单位',
    'Section': '部分',
    'Branch': '分支',
    'Office': '办公室',
    'Location': '位置',
    'Address': '地址',
    'Phone': '电话',
    'Fax': '传真',
    'Email': '邮箱',
    'Website': '网站',
    'Social media': '社交媒体',
    'Blog': '博客',
    'Forum': '论坛',
    'Community': '社区',
    'Network': '网络',
    'Partners': '合作伙伴',
    'Clients': '客户',
    'Customers': '客户',
    'Users': '用户',
    'Visitors': '访客',
    'Members': '成员',
    'Subscribers': '订阅者',
    'Followers': '关注者',
    'Fans': '粉丝',
    'Friends': '朋友',
    'Contacts': '联系人',
    'Leads': '线索',
    'Prospects': '潜在客户',
    'Opportunities': '机会',
    'Deals': '交易',
    'Sales': '销售',
    'Revenue': '收入',
    'Profit': '利润',
    'Loss': '亏损',
    'Budget': '预算',
    'Cost': '成本',
    'Price': '价格',
    'Rate': '费率',
    'Fee': '费用',
    'Charge': '收费',
    'Payment': '付款',
    'Invoice': '发票',
    'Receipt': '收据',
    'Bill': '账单',
    'Transaction': '交易',
    'Order': '订单',
    'Purchase': '购买',
    'Sale': '销售',
    'Discount': '折扣',
    'Offer': '优惠',
    'Promotion': '促销',
    'Campaign': '活动',
    'Marketing': '营销',
    'Advertising': '广告',
    'Branding': '品牌',
    'Product': '产品',
    'Service': '服务',
    'Solution': '解决方案',
    'Feature': '功能',
    'Benefit': '好处',
    'Advantage': '优势',
    'Value': '价值',
    'Quality': '质量',
    'Standard': '标准',
    'Certification': '认证',
    'Warranty': '保修',
    'Guarantee': '保证',
    'Support': '支持',
    'Maintenance': '维护',
    'Update': '更新',
    'Upgrade': '升级',
    'Version': '版本',
    'Release': '发布',
    'Launch': '启动',
    'Introduction': '介绍',
    'Announcement': '公告',
    'News': '新闻',
    'Press': '新闻',
    'Media': '媒体',
    'Coverage': '报道',
    'Article': '文章',
    'Post': '帖子',
    'Story': '故事',
    'Blog': '博客',
    'Review': '评论',
    'Rating': '评级',
    'Testimonial': '推荐',
    'Feedback': '反馈',
    'Comment': '评论',
    'Opinion': '意见',
    'Suggestion': '建议',
    'Idea': '想法',
    'Proposal': '提案',
    'Request': '请求',
    'Inquiry': '询问',
    'Question': '问题',
    'Answer': '答案',
    'Response': '回复',
    'Reply': '回复',
    'Contact': '联系',
    'Message': '消息',
    'Notification': '通知',
    'Alert': '警报',
    'Reminder': '提醒',
    'Warning': '警告',
    'Error': '错误',
    'Issue': '问题',
    'Problem': '问题',
    'Bug': '错误',
    'Glitch': '故障',
    'Crash': '崩溃',
    'Failure': '失败',
    'Success': '成功',
    'Achievement': '成就',
    'Milestone': '里程碑',
    'Goal': '目标',
    'Objective': '目标',
    'Target': '目标',
    'Destination': '目的地',
    'Purpose': '目的',
    'Mission': '使命',
    'Vision': '愿景',
    'Strategy': '策略',
    'Plan': '计划',
    'Schedule': '计划',
    'Timeline': '时间线',
    'Deadline': '截止日期',
    'Delivery': '交付',
    'Deployment': '部署',
    'Installation': '安装',
    'Setup': '设置',
    'Configuration': '配置',
    'Customization': '自定义',
    'Integration': '集成',
    'Connection': '连接',
    'Interface': '接口',
    'API': 'API',
    'SDK': 'SDK',
    'Library': '库',
    'Framework': '框架',
    'Platform': '平台',
    'System': '系统',
    'Software': '软件',
    'Application': '应用程序',
    'Tool': '工具',
    'Utility': '实用程序',
    'Plugin': '插件',
    'Extension': '扩展',
    'Addon': '附加组件',
    'Module': '模块',
    'Component': '组件',
    'Widget': '小部件',
    'Element': '元素',
    'Control': '控件',
    'Feature': '功能',
    'Function': '功能',
    'Capability': '能力',
    'Option': '选项',
    'Setting': '设置',
    'Parameter': '参数',
    'Property': '属性',
    'Attribute': '属性',
    'Characteristic': '特征',
    'Trait': '特性',
    'Behavior': '行为',
    'Action': '动作',
    'Operation': '操作',
    'Activity': '活动',
    'Task': '任务',
    'Job': '工作',
    'Process': '过程',
    'Workflow': '工作流',
    'Pipeline': '管道',
    'Channel': '频道',
    'Stream': '流',
    'Flow': '流',
    'Path': '路径',
    'Route': '路线',
    'Way': '方式',
    'Method': '方法',
    'Approach': '方法',
    'Technique': '技术',
    'Algorithm': '算法',
    'Formula': '公式',
    'Calculation': '计算',
    'Computation': '计算',
    'Processing': '处理',
    'Analysis': '分析',
    'Examination': '检查',
    'Evaluation': '评估',
    'Assessment': '评估',
    'Review': '审查',
    'Audit': '审计',
    'Inspection': '检查',
    'Verification': '验证',
    'Validation': '验证',
    'Testing': '测试',
    'Debugging': '调试',
    'Troubleshooting': '故障排除',
    'Optimization': '优化',
    'Improvement': '改进',
    'Enhancement': '增强',
    'Modification': '修改',
    'Adjustment': '调整',
    'Tuning': '调整',
    'Calibration': '校准',
    'Configuration': '配置',
    'Setup': '设置',
    'Installation': '安装',
    'Deployment': '部署',
    'Implementation': '实施',
    'Execution': '执行',
    'Performance': '性能',
    'Speed': '速度',
    'Efficiency': '效率',
    'Productivity': '生产力',
    'Capacity': '容量',
    'Scalability': '可扩展性',
    'Reliability': '可靠性',
    'Availability': '可用性',
    'Stability': '稳定性',
    'Security': '安全性',
    'Privacy': '隐私性',
    'Compliance': '合规性',
    'Compatibility': '兼容性',
    'Interoperability': '互操作性',
    'Accessibility': '可访问性',
    'Usability': '易用性',
    'User experience': '用户体验',
    'Interface': '界面',
    'Design': '设计',
    'Layout': '布局',
    'Appearance': '外观',
    'Style': '样式',
    'Theme': '主题',
    'Color': '颜色',
    'Font': '字体',
    'Size': '大小',
    'Shape': '形状',
    'Position': '位置',
    'Location': '位置',
    'Placement': '放置',
    'Alignment': '对齐',
    'Orientation': '方向',
    'Direction': '方向',
    'Order': '顺序',
    'Sequence': '序列',
    'Arrangement': '排列',
    'Organization': '组织',
    'Structure': '结构',
    'Hierarchy': '层次结构',
    'Relationship': '关系',
    'Association': '关联',
    'Connection': '连接',
    'Link': '链接',
    'Bond': '绑定',
    'Attachment': '附件',
    'Dependency': '依赖',
    'Reference': '引用',
    'Pointer': '指针',
    'Index': '索引',
    'Key': '键',
    'Value': '值',
    'Pair': '对',
    'Entry': '条目',
    'Record': '记录',
    'Row': '行',
    'Column': '列',
    'Cell': '单元格',
    'Field': '字段',
    'Property': '属性',
    'Attribute': '属性',
    'Characteristic': '特征',
    'Feature': '功能',
    'Aspect': '方面',
    'Element': '元素',
    'Component': '组件',
    'Part': '部分',
    'Piece': '片段',
    'Section': '部分',
    'Segment': '段',
    'Division': '部门',
    'Category': '分类',
    'Class': '类',
    'Type': '类型',
    'Kind': '种类',
    'Sort': '种类',
    'Variety': '品种',
    'Version': '版本',
    'Edition': '版本',
    'Release': '发布',
    'Update': '更新',
    'Patch': '补丁',
    'Fix': '修复',
    'Correction': '更正',
    'Improvement': '改进',
    'Enhancement': '增强',
    'Addition': '添加',
    'Extension': '扩展',
    'Expansion': '扩展',
    'Modification': '修改',
    'Change': '更改',
    'Revision': '修订',
    'Alteration': '更改',
    'Adjustment': '调整',
    'Adaptation': '适应',
    'Customization': '自定义',
    'Personalization': '个性化',
    'Optimization': '优化',
    'Refinement': '改进',
    'Polish': '完善',
    'Cleanup': '清理',
    'Maintenance': '维护',
    'Support': '支持',
    'Service': '服务',
    'Assistance': '协助',
    'Help': '帮助',
    'Guidance': '指导',
    'Advice': '建议',
    'Recommendation': '推荐',
    'Suggestion': '建议',
    'Proposal': '提案',
    'Offer': '提供',
    'Deal': '交易',
    'Agreement': '协议',
    'Contract': '合同',
    'Terms': '条款',
    'Conditions': '条件',
    'Requirements': '要求',
    'Specifications': '规格',
    'Standards': '标准',
    'Guidelines': '指导方针',
    'Rules': '规则',
    'Regulations': '法规',
    'Policies': '政策',
    'Procedures': '程序',
    'Protocols': '协议',
    'Conventions': '约定',
    'Best practices': '最佳实践',
    'Standards': '标准',
    'Quality': '质量',
    'Excellence': '卓越',
    'Performance': '性能',
    'Efficiency': '效率',
    'Effectiveness': '有效性',
    'Productivity': '生产力',
    'Success': '成功',
    'Achievement': '成就',
    'Result': '结果',
    'Outcome': '结果',
    'Impact': '影响',
    'Benefit': '好处',
    'Advantage': '优势',
    'Value': '价值',
    'Worth': '价值',
    'Merit': '优点',
    'Strength': '优势',
    'Capability': '能力',
    'Competence': '能力',
    'Skill': '技能',
    'Expertise': '专业知识',
    'Knowledge': '知识',
    'Information': '信息',
    'Data': '数据',
    'Content': '内容',
    'Material': '材料',
    'Resource': '资源',
    'Asset': '资产',
    'Property': '财产',
    'Belonging': '所属',
    'Possession': '拥有',
    'Ownership': '所有权',
    'Control': '控制',
    'Management': '管理',
    'Administration': '管理',
    'Governance': '治理',
    'Oversight': '监督',
    'Supervision': '监督',
    'Direction': '指导',
    'Leadership': '领导',
    'Guidance': '指导',
    'Mentorship': '指导',
    'Coaching': '辅导',
    'Training': '培训',
    'Education': '教育',
    'Learning': '学习',
    'Development': '发展',
    'Growth': '增长',
    'Progress': '进展',
    'Advancement': '进步',
    'Improvement': '改进',
    'Enhancement': '增强',
    'Innovation': '创新',
    'Creativity': '创造力',
    'Inspiration': '灵感',
    'Ideation': '创意',
    'Brainstorming': '头脑风暴',
    'Collaboration': '协作',
    'Cooperation': '合作',
    'Partnership': '伙伴关系',
    'Teamwork': '团队合作',
    'Synergy': '协同',
    'Coordination': '协调',
    'Communication': '沟通',
    'Interaction': '互动',
    'Engagement': '参与',
    'Participation': '参与',
    'Involvement': '参与',
    'Contribution': '贡献',
    'Input': '输入',
    'Feedback': '反馈',
    'Review': '审查',
    'Evaluation': '评估',
    'Assessment': '评估',
    'Analysis': '分析',
    'Research': '研究',
    'Investigation': '调查',
    'Study': '学习',
    'Examination': '检查',
    'Inspection': '检查',
    'Audit': '审计',
    'Verification': '验证',
    'Validation': '验证',
    'Testing': '测试',
    'Quality assurance': '质量保证',
    'Quality control': '质量控制',
    'Quality management': '质量管理',
    'Process improvement': '流程改进',
    'Continuous improvement': '持续改进',
    'Optimization': '优化',
    'Efficiency': '效率',
    'Productivity': '生产力',
    'Performance': '性能',
    'Effectiveness': '有效性',
    'Success': '成功',
    'Excellence': '卓越',
    'Quality': '质量',
    'Standards': '标准',
    'Compliance': '合规',
    'Regulation': '法规',
    'Policy': '政策',
    'Procedure': '程序',
    'Protocol': '协议',
    'Guideline': '指导方针',
    'Best practice': '最佳实践',
    'Framework': '框架',
    'Methodology': '方法论',
    'Approach': '方法',
    'Strategy': '策略',
    'Tactic': '战术',
    'Plan': '计划',
    'Roadmap': '路线图',
    'Vision': '愿景',
    'Mission': '使命',
    'Goal': '目标',
    'Objective': '目标',
    'Target': '目标',
    'Milestone': '里程碑',
    'Deadline': '截止日期',
    'Timeline': '时间线',
    'Schedule': '计划',
    'Calendar': '日历',
    'Agenda': '议程',
    'Meeting': '会议',
    'Conference': '会议',
    'Workshop': '研讨会',
    'Seminar': '研讨会',
    'Training': '培训',
    'Course': '课程',
    'Program': '程序',
    'Curriculum': '课程',
    'Syllabus': '教学大纲',
    'Lesson': '课程',
    'Tutorial': '教程',
    'Guide': '指南',
    'Manual': '手册',
    'Documentation': '文档',
    'Reference': '参考',
    'Resource': '资源',
    'Material': '材料',
    'Content': '内容',
    'Information': '信息',
    'Data': '数据',
    'Statistics': '统计',
    'Metrics': '指标',
    'Analytics': '分析',
    'Reporting': '报告',
    'Dashboard': '仪表板',
    'Overview': '概览',
    'Summary': '摘要',
    'Details': '详情',
    'Insights': '洞察',
    'Findings': '发现',
    'Results': '结果',
    'Outcomes': '结果',
    'Conclusions': '结论',
    'Recommendations': '建议',
    'Action items': '行动项目',
    'Next steps': '下一步',
    'Follow-up': '跟进',
    'Implementation': '实施',
    'Execution': '执行',
    'Deployment': '部署',
    'Launch': '启动',
    'Release': '发布',
    'Delivery': '交付',
    'Completion': '完成',
    'Achievement': '成就',
    'Success': '成功',
    'Recognition': '认可',
    'Award': '奖励',
    'Certification': '认证',
    'Accreditation': '认可',
    'License': '许可证',
    'Permission': '许可',
    'Approval': '批准',
    'Authorization': '授权',
    'Access': '访问',
    'Entry': '进入',
    'Admission': '进入',
    'Registration': '注册',
    'Enrollment': '注册',
    'Subscription': '订阅',
    'Membership': '会员资格',
    'Participation': '参与',
    'Involvement': '参与',
    'Engagement': '参与',
    'Interaction': '互动',
    'Communication': '沟通',
    'Collaboration': '协作',
    'Cooperation': '合作',
    'Partnership': '伙伴关系',
    'Alliance': '联盟',
    'Network': '网络',
    'Community': '社区',
    'Group': '组',
    'Team': '团队',
    'Organization': '组织',
    'Company': '公司',
    'Business': '业务',
    'Enterprise': '企业',
    'Corporation': '公司',
    'Institution': '机构',
    'Agency': '机构',
    'Department': '部门',
    'Division': '部门',
    'Unit': '单位',
    'Office': '办公室',
    'Branch': '分支',
    'Location': '位置',
    'Facility': '设施',
    'Site': '站点',
    'Campus': '园区',
    'Building': '建筑',
    'Complex': '综合体',
    'Center': '中心',
    'Hub': '中心',
    'Station': '站点',
    'Terminal': '终端',
    'Port': '端口',
    'Gateway': '网关',
    'Bridge': '桥梁',
    'Link': '链接',
    'Connection': '连接',
    'Interface': '接口',
    'Integration': '集成',
    'Synchronization': '同步',
    'Coordination': '协调',
    'Harmonization': '协调',
    'Standardization': '标准化',
    'Normalization': '规范化',
    'Optimization': '优化',
    'Automation': '自动化',
    'Digitization': '数字化',
    'Transformation': '转型',
    'Modernization': '现代化',
    'Innovation': '创新',
    'Evolution': '演进',
    'Revolution': '革命',
    'Disruption': '颠覆',
    'Breakthrough': '突破',
    'Advancement': '进步',
    'Progress': '进展',
    'Development': '发展',
    'Growth': '增长',
    'Expansion': '扩展',
    'Diversification': '多元化',
    'Specialization': '专业化',
    'Customization': '自定义',
    'Personalization': '个性化',
    'Localization': '本地化',
    'Globalization': '全球化',
    'Internationalization': '国际化',
    'Standardization': '标准化',
    'Regulation': '监管',
    'Compliance': '合规',
    'Governance': '治理',
    'Oversight': '监督',
    'Transparency': '透明度',
    'Accountability': '问责制',
    'Responsibility': '责任',
    'Sustainability': '可持续性',
    'Efficiency': '效率',
    'Effectiveness': '有效性',
    'Productivity': '生产力',
    'Performance': '性能',
    'Quality': '质量',
    'Excellence': '卓越',
    'Innovation': '创新',
    'Creativity': '创造力',
    'Leadership': '领导力',
    'Management': '管理',
    'Strategy': '策略',
    'Planning': '规划',
    'Execution': '执行',
    'Operations': '运营',
    'Processes': '流程',
    'Systems': '系统',
    'Technology': '技术',
    'Infrastructure': '基础设施',
    'Platform': '平台',
    'Architecture': '架构',
    'Design': '设计',
    'Development': '开发',
    'Implementation': '实施',
    'Testing': '测试',
    'Deployment': '部署',
    'Maintenance': '维护',
    'Support': '支持',
    'Service': '服务',
    'Delivery': '交付',
    'Customer': '客户',
    'User': '用户',
    'Experience': '体验',
    'Satisfaction': '满意度',
    'Loyalty': '忠诚度',
    'Retention': '保留',
    'Acquisition': '获取',
    'Conversion': '转化',
    'Engagement': '参与',
    'Interaction': '互动',
    'Communication': '沟通',
    'Feedback': '反馈',
    'Review': '评论',
    'Rating': '评级',
    'Reputation': '声誉',
    'Brand': '品牌',
    'Image': '形象',
    'Identity': '身份',
    'Presence': '存在',
    'Visibility': '可见性',
    'Awareness': '意识',
    'Recognition': '认可',
    'Trust': '信任',
    'Credibility': '可信度',
    'Reliability': '可靠性',
    'Consistency': '一致性',
    'Quality': '质量',
    'Value': '价值',
    'Benefits': '好处',
    'Features': '功能',
    'Advantages': '优势',
    'Strengths': '优势',
    'Opportunities': '机会',
    'Threats': '威胁',
    'Weaknesses': '弱点',
    'Challenges': '挑战',
    'Risks': '风险',
    'Issues': '问题',
    'Problems': '问题',
    'Solutions': '解决方案',
    'Alternatives': '替代方案',
    'Options': '选项',
    'Choices': '选择',
    'Decisions': '决策',
    'Actions': '行动',
    'Steps': '步骤',
    'Measures': '措施',
    'Initiatives': '倡议',
    'Projects': '项目',
    'Programs': '程序',
    'Campaigns': '活动',
    'Efforts': '努力',
    'Attempts': '尝试',
    'Trials': '试验',
    'Experiments': '实验',
    'Tests': '测试',
    'Pilots': '试点',
    'Prototypes': '原型',
    'Models': '模型',
    'Samples': '样品',
    'Examples': '示例',
    'Cases': '案例',
    'Studies': '研究',
    'Analyses': '分析',
    'Reports': '报告',
    'Findings': '发现',
    'Results': '结果',
    'Outcomes': '结果',
    'Impacts': '影响',
    'Effects': '效果',
    'Consequences': '后果',
    'Implications': '影响',
    'Significance': '重要性',
    'Importance': '重要性',
    'Priority': '优先级',
    'Urgency': '紧急性',
    'Necessity': '必要性',
    'Requirement': '要求',
    'Need': '需求',
    'Demand': '需求',
    'Supply': '供应',
    'Availability': '可用性',
    'Accessibility': '可访问性',
    'Affordability': '可负担性',
    'Suitability': '适用性',
    'Appropriateness': '适当性',
    'Relevance': '相关性',
    'Applicability': '适用性',
    'Compatibility': '兼容性',
    'Interoperability': '互操作性',
    'Scalability': '可扩展性',
    'Flexibility': '灵活性',
    'Adaptability': '适应性',
    'Versatility': '多功能性',
    'Portability': '可移植性',
    'Mobility': '移动性',
    'Agility': '敏捷性',
    'Responsiveness': '响应性',
    'Proactivity': '主动性',
    'Reactivity': '反应性',
    'Timeliness': '及时性',
    'Accuracy': '准确性',
    'Precision': '精确性',
    'Reliability': '可靠性',
    'Validity': '有效性',
    'Integrity': '完整性',
    'Security': '安全性',
    'Privacy': '隐私性',
    'Confidentiality': '机密性',
    'Authenticity': '真实性',
    'Transparency': '透明度',
    'Accountability': '问责制',
    'Responsibility': '责任',
    'Ownership': '所有权',
    'Commitment': '承诺',
    'Dedication': '奉献',
    'Excellence': '卓越',
    'Quality': '质量',
    'Improvement': '改进',
    'Enhancement': '增强',
    'Innovation': '创新',
    'Creativity': '创造力',
    'Collaboration': '协作',
    'Teamwork': '团队合作',
    'Partnership': '伙伴关系',
    'Synergy': '协同',
    'Cooperation': '合作',
    'Coordination': '协调',
    'Communication': '沟通',
    'Information': '信息',
    'Knowledge': '知识',
    'Learning': '学习',
    'Development': '发展',
    'Growth': '增长',
    'Progress': '进展',
    'Success': '成功',
    'Achievement': '成就',
    'Performance': '性能',
    'Results': '结果',
    'Impact': '影响',
    'Value': '价值',
    'Contribution': '贡献',
    'Difference': '差异',
    'Change': '变化',
    'Transformation': '转型',
    'Evolution': '演进',
    'Revolution': '革命',
    'Innovation': '创新',
    'Breakthrough': '突破',
    'Discovery': '发现',
    'Exploration': '探索',
    'Adventure': '冒险',
    'Journey': '旅程',
    'Experience': '体验',
    'Memory': '记忆',
    'History': '历史',
    'Tradition': '传统',
    'Culture': '文化',
    'Heritage': '遗产',
    'Legacy': '遗产',
    'Future': '未来',
    'Vision': '愿景',
    'Dream': '梦想',
    'Aspiration': '抱负',
    'Ambition': '雄心',
    'Goal': '目标',
    'Target': '目标',
    'Objective': '目标',
    'Purpose': '目的',
    'Mission': '使命',
    'Calling': '使命',
    'Passion': '激情',
    'Enthusiasm': '热情',
    'Motivation': '动机',
    'Inspiration': '灵感',
    'Creativity': '创造力',
    'Imagination': '想象力',
    'Innovation': '创新',
    'Ingenuity': '独创性',
    'Resourcefulness': '足智多谋',
    'Versatility': '多功能性',
    'Adaptability': '适应性',
    'Flexibility': '灵活性',
    'Agility': '敏捷性',
    'Resilience': '韧性',
    'Perseverance': '毅力',
    'Determination': '决心',
    'Commitment': '承诺',
    'Dedication': '奉献',
    'Excellence': '卓越',
    'Quality': '质量',
    'Integrity': '完整性',
    'Honesty': '诚实',
    'Transparency': '透明度',
    'Authenticity': '真实性',
    'Trustworthiness': '可信度',
    'Reliability': '可靠性',
    'Dependability': '可靠性',
    'Consistency': '一致性',
    'Stability': '稳定性',
    'Sustainability': '可持续性',
    'Efficiency': '效率',
    'Effectiveness': '有效性',
    'Productivity': '生产力',
    'Performance': '性能',
    'Success': '成功',
    'Achievement': '成就',
    'Accomplishment': '成就',
    'Fulfillment': '满足',
    'Satisfaction': '满意',
    'Happiness': '幸福',
    'Well-being': '福祉',
    'Prosperity': '繁荣',
    'Growth': '增长',
    'Development': '发展',
    'Progress': '进展',
    'Advancement': '进步',
    'Improvement': '改进',
    'Enhancement': '增强',
    'Optimization': '优化',
    'Refinement': '完善',
    'Perfection': '完美',
    'Mastery': '精通',
    'Expertise': '专业知识',
    'Skill': '技能',
    'Talent': '天赋',
    'Ability': '能力',
    'Capability': '能力',
    'Competence': '能力',
    'Proficiency': '熟练',
    'Excellence': '卓越',
    'Superiority': '优势',
    'Leadership': '领导力',
    'Management': '管理',
    'Supervision': '监督',
    'Guidance': '指导',
    'Mentorship': '指导',
    'Coaching': '辅导',
    'Training': '培训',
    'Education': '教育',
    'Learning': '学习',
    'Knowledge': '知识',
    'Wisdom': '智慧',
    'Understanding': '理解',
    'Insight': '洞察',
    'Awareness': '意识',
    'Consciousness': '意识',
    'Mindfulness': '正念',
    'Focus': '专注',
    'Attention': '注意力',
    'Concentration': '专注',
    'Clarity': '清晰',
    'Vision': '愿景',
    'Perspective': '视角',
    'Viewpoint': '观点',
    'Opinion': '意见',
    'Belief': '信念',
    'Faith': '信仰',
    'Trust': '信任',
    'Confidence': '信心',
    'Assurance': '保证',
    'Certainty': '确定性',
    'Security': '安全性',
    'Safety': '安全',
    'Protection': '保护',
    'Care': '关心',
    'Support': '支持',
    'Help': '帮助',
    'Assistance': '协助',
    'Service': '服务',
    'Contribution': '贡献',
    'Participation': '参与',
    'Involvement': '参与',
    'Engagement': '参与',
    'Interaction': '互动',
    'Communication': '沟通',
    'Connection': '连接',
    'Relationship': '关系',
    'Partnership': '伙伴关系',
    'Collaboration': '协作',
    'Cooperation': '合作',
    'Teamwork': '团队合作',
    'Synergy': '协同',
    'Unity': '团结',
    'Solidarity': '团结',
    'Community': '社区',
    'Belonging': '归属',
    'Inclusion': '包容',
    'Diversity': '多样性',
    'Equality': '平等',
    'Fairness': '公平',
    'Justice': '正义',
    'Freedom': '自由',
    'Independence': '独立',
    'Autonomy': '自主',
    'Empowerment': '赋权',
    'Enablement': '赋能',
    'Opportunity': '机会',
    'Potential': '潜力',
    'Possibility': '可能性',
    'Prospect': '前景',
    'Future': '未来',
    'Hope': '希望',
    'Optimism': '乐观',
    'Positivity': '积极性',
    'Enthusiasm': '热情',
    'Passion': '激情',
    'Energy': '能量',
    'Vitality': '活力',
    'Dynamism': '活力',
    'Momentum': '势头',
    'Progress': '进展',
    'Movement': '运动',
    'Action': '行动',
    'Activity': '活动',
    'Initiative': '主动性',
    'Proactivity': '主动性',
    'Leadership': '领导力',
    'Influence': '影响力',
    'Impact': '影响',
    'Effect': '效果',
    'Result': '结果',
    'Outcome': '结果',
    'Achievement': '成就',
    'Success': '成功',
    'Victory': '胜利',
    'Triumph': '胜利',
    'Accomplishment': '成就',
    'Fulfillment': '满足',
    'Realization': '实现',
    'Actualization': '实现',
    'Manifestation': '体现',
    'Expression': '表达',
    'Communication': '沟通',
    'Articulation': '表达',
    'Presentation': '展示',
    'Demonstration': '演示',
    'Illustration': '说明',
    'Explanation': '解释',
    'Description': '描述',
    'Narration': '叙述',
    'Storytelling': '讲故事',
    'Sharing': '分享',
    'Teaching': '教学',
    'Learning': '学习',
    'Guiding': '指导',
    'Mentoring': '指导',
    'Coaching': '辅导',
    'Supporting': '支持',
    'Encouraging': '鼓励',
    'Inspiring': '激励',
    'Motivating': '激励',
    'Empowering': '赋权',
    'Enabling': '赋能',
    'Facilitating': '促进',
    'Organizing': '组织',
    'Planning': '规划',
    'Coordinating': '协调',
    'Managing': '管理',
    'Leading': '领导',
    'Directing': '指导',
    'Guiding': '指导',
    'Advising': '建议',
    'Consulting': '咨询',
    'Assisting': '协助',
    'Helping': '帮助',
    'Serving': '服务',
    'Contributing': '贡献',
    'Participating': '参与',
    'Engaging': '参与',
    'Interacting': '互动',
    'Connecting': '连接',
    'Networking': '建立人脉',
    'Building': '建立',
    'Creating': '创建',
    'Developing': '开发',
    'Growing': '增长',
    'Evolving': '演进',
    'Transforming': '转型',
    'Improving': '改进',
    'Enhancing': '增强',
    'Optimizing': '优化',
    'Refining': '完善',
    'Perfecting': '完善',
    'Mastering': '精通',
    'Learning': '学习',
    'Discovering': '发现',
    'Exploring': '探索',
    'Innovating': '创新',
    'Creating': '创建',
    'Designing': '设计',
    'Building': '构建',
    'Implementing': '实施',
    'Executing': '执行',
    'Delivering': '交付',
    'Achieving': '实现',
    'Succeeding': '成功',
    'Winning': '获胜',
    'Excelling': '卓越',
    'Leading': '领导',
    'Inspiring': '激励',
    'Motivating': '激励',
    'Influencing': '影响',
    'Impacting': '影响',
    'Changing': '改变',
    'Transforming': '转型',
    'Revolutionizing': '革命化',
    'Innovating': '创新',
    'Disrupting': '颠覆',
    'Breaking': '突破',
    'Creating': '创建',
    'Building': '构建',
    'Developing': '开发',
    'Growing': '增长',
    'Succeeding': '成功',
    'Thriving': '蓬勃发展',
    'Flourishing': '繁荣',
    'Prospering': '繁荣',
    'Excelling': '卓越',
    'Leading': '领导',
    'Winning': '获胜',
    'Achieving': '实现',
    'Accomplishing': '完成',
    'Completing': '完成',
    'Finishing': '完成',
    'Concluding': '结束',
    'Closing': '关闭',
    'Ending': '结束',
    'Starting': '开始',
    'Beginning': '开始',
    'Launching': '启动',
    'Initiating': '启动',
    'Opening': '打开',
    'Beginning': '开始',
    'Commencing': '开始',
    'Embarking': '开始',
    'Venturing': '冒险',
    'Exploring': '探索',
    'Discovering': '发现',
    'Learning': '学习',
    'Growing': '增长',
    'Developing': '开发',
    'Evolving': '演进',
    'Progressing': '进展',
    'Advancing': '前进',
    'Moving': '移动',
    'Changing': '改变',
    'Transforming': '转型',
    'Improving': '改进',
    'Enhancing': '增强',
    'Optimizing': '优化',
    'Perfecting': '完善',
    'Mastering': '精通',
    'Becoming': '成为',
    'Achieving': '实现',
    'Reaching': '达到',
    'Attaining': '获得',
    'Gaining': '获得',
    'Acquiring': '获取',
    'Obtaining': '获得',
    'Securing': '确保',
    'Ensuring': '确保',
    'Guaranteeing': '保证',
    'Providing': '提供',
    'Delivering': '交付',
    'Offering': '提供',
    'Presenting': '展示',
    'Sharing': '分享',
    'Communicating': '沟通',
    'Connecting': '连接',
    'Building': '建立',
    'Creating': '创建',
    'Developing': '开发',
    'Innovating': '创新',
    'Leading': '领导',
    'Inspiring': '激励',
    'Motivating': '激励',
    'Empowering': '赋权',
    'Enabling': '赋能',
    'Supporting': '支持',
    'Helping': '帮助',
    'Assisting': '协助',
    'Serving': '服务',
    'Contributing': '贡献',
    'Participating': '参与',
    'Engaging': '参与',
    'Interacting': '互动',
    'Collaborating': '协作',
    'Cooperating': '合作',
    'Partnering': '合作',
    'Teaming': '组队',
    'Working': '工作',
    'Striving': '努力',
    'Trying': '尝试',
    'Attempting': '尝试',
    'Endeavoring': '努力',
    'Pursuing': '追求',
    'Seeking': '寻求',
    'Searching': '搜索',
    'Looking': '寻找',
    'Exploring': '探索',
    'Investigating': '调查',
    'Researching': '研究',
    'Studying': '学习',
    'Analyzing': '分析',
    'Examining': '检查',
    'Inspecting': '检查',
    'Reviewing': '审查',
    'Evaluating': '评估',
    'Assessing': '评估',
    'Judging': '判断',
    'Deciding': '决定',
    'Choosing': '选择',
    'Selecting': '选择',
    'Picking': '挑选',
    'Opting': '选择',
    'Preferring': '偏好',
    'Favoring': '偏爱',
    'Liking': '喜欢',
    'Enjoying': '享受',
    'Appreciating': '欣赏',
    'Valuing': '重视',
    'Treasuring': '珍惜',
    'Cherishing': '珍爱',
    'Protecting': '保护',
    'Preserving': '保护',
    'Maintaining': '维护',
    'Keeping': '保持',
    'Retaining': '保留',
    'Holding': '持有',
    'Grasping': '理解',
    'Understanding': '理解',
    'Comprehending': '理解',
    'Realizing': '意识到',
    'Recognizing': '认识到',
    'Identifying': '识别',
    'Noticing': '注意到',
    'Observing': '观察',
    'Seeing': '看见',
    'Viewing': '查看',
    'Watching': '观看',
    'Looking': '看',
    'Noting': '注意',
    'Recording': '记录',
    'Documenting': '记录',
    'Reporting': '报告',
    'Describing': '描述',
    'Explaining': '解释',
    'Illustrating': '说明',
    'Demonstrating': '演示',
    'Showing': '展示',
    'Presenting': '展示',
    'Displaying': '显示',
    'Revealing': '揭示',
    'Uncovering': '发现',
    'Discovering': '发现',
    'Finding': '查找',
    'Locating': '定位',
    'Identifying': '识别',
    'Recognizing': '识别',
    'Distinguishing': '区分',
    'Differentiating': '区分',
    'Comparing': '比较',
    'Contrasting': '对比',
    'Matching': '匹配',
    'Aligning': '对齐',
    'Coordinating': '协调',
    'Synchronizing': '同步',
    'Harmonizing': '协调',
    'Balancing': '平衡',
    'Adjusting': '调整',
    'Adapting': '适应',
    'Modifying': '修改',
    'Changing': '改变',
    'Updating': '更新',
    'Upgrading': '升级',
    'Improving': '改进',
    'Enhancing': '增强',
    'Optimizing': '优化',
    'Refining': '完善',
    'Perfecting': '完善',
    'Polishing': '完善',
    'Finishing': '完成',
    'Completing': '完成',
    'Finalizing': '完成',
    'Concluding': '结束',
    'Closing': '关闭',
    'Wrapping up': '收尾',
    'Summarizing': '总结',
    'Recapping': '回顾',
    'Reviewing': '审查',
    'Reflecting': '反思',
    'Considering': '考虑',
    'Thinking': '思考',
    'Pondering': '思考',
    'Contemplating': '思考',
    'Meditating': '冥想',
    'Focusing': '专注',
    'Concentrating': '专注',
    'Paying attention': '注意',
    'Listening': '倾听',
    'Hearing': '听到',
    'Understanding': '理解',
    'Grasping': '理解',
    'Comprehending': '理解',
    'Learning': '学习',
    'Studying': '学习',
    'Practicing': '练习',
    'Training': '培训',
    'Preparing': '准备',
    'Getting ready': '准备',
    'Planning': '规划',
    'Organizing': '组织',
    'Arranging': '安排',
    'Scheduling': '安排',
    'Coordinating': '协调',
    'Managing': '管理',
    'Handling': '处理',
    'Dealing with': '处理',
    'Addressing': '处理',
    'Tackling': '处理',
    'Confronting': '面对',
    'Facing': '面对',
    'Encountering': '遇到',
    'Meeting': '见面',
    'Engaging': '参与',
    'Participating': '参与',
    'Joining': '加入',
    'Contributing': '贡献',
    'Adding': '添加',
    'Providing': '提供',
    'Offering': '提供',
    'Giving': '给予',
    'Delivering': '交付',
    'Presenting': '展示',
    'Sharing': '分享',
    'Communicating': '沟通',
    'Expressing': '表达',
    'Articulating': '表达',
    'Conveying': '传达',
    'Transmitting': '传输',
    'Sending': '发送',
    'Receiving': '接收',
    'Getting': '获得',
    'Obtaining': '获得',
    'Acquiring': '获取',
    'Gaining': '获得',
    'Earning': '赚取',
    'Winning': '获胜',
    'Achieving': '实现',
    'Reaching': '达到',
    'Attaining': '获得',
    'Securing': '确保',
    'Ensuring': '确保',
    'Guaranteeing': '保证',
    'Promising': '承诺',
    'Committing': '承诺',
    'Dedicating': '奉献',
    'Devoting': '奉献',
    'Investing': '投资',
    'Contributing': '贡献',
    'Supporting': '支持',
    'Backing': '支持',
    'Helping': '帮助',
    'Assisting': '协助',
    'Aiding': '帮助',
    'Facilitating': '促进',
    'Enabling': '赋能',
    'Empowering': '赋权',
    'Inspiring': '激励',
    'Motivating': '激励',
    'Encouraging': '鼓励',
    'Uplifting': '提升',
    'Elevating': '提升',
    'Raising': '提高',
    'Improving': '改进',
    'Enhancing': '增强',
    'Strengthening': '加强',
    'Reinforcing': '加强',
    'Supporting': '支持',
    'Sustaining': '维持',
    'Maintaining': '维护',
    'Preserving': '保护',
    'Protecting': '保护',
    'Defending': '保护',
    'Guarding': '守护',
    'Keeping': '保持',
    'Holding': '持有',
    'Retaining': '保留',
    'Saving': '保存',
    'Storing': '存储',
    'Keeping': '保持',
    'Maintaining': '维护',
    'Continuing': '继续',
    'Persisting': '坚持',
    'Persevering': '坚持',
    'Enduring': '坚持',
    'Withstanding': '承受',
    'Surviving': '幸存',
    'Thriving': '蓬勃发展',
    'Flourishing': '繁荣',
    'Prospering': '繁荣',
    'Succeeding': '成功',
    'Winning': '获胜',
    'Triumphing': '胜利',
    'Prevailing': '占优势',
    'Dominating': '主导',
    'Leading': '领导',
    'Guiding': '指导',
    'Directing': '指导',
    'Steering': '引导',
    'Navigating': '导航',
    'Charting': '规划',
    'Mapping': '映射',
    'Planning': '规划',
    'Designing': '设计',
    'Creating': '创建',
    'Building': '构建',
    'Constructing': '构建',
    'Assembling': '组装',
    'Putting together': '组合',
    'Combining': '组合',
    'Merging': '合并',
    'Integrating': '集成',
    'Unifying': '统一',
    'Consolidating': '整合',
    'Amalgamating': '合并',
    'Blending': '混合',
    'Mixing': '混合',
    'Joining': '连接',
    'Connecting': '连接',
    'Linking': '链接',
    'Bonding': '绑定',
    'Attaching': '附加',
    'Fastening': '固定',
    'Securing': '确保',
    'Anchoring': '锚定',
    'Grounding': '基础',
    'Founding': '建立',
    'Establishing': '建立',
    'Setting up': '设置',
    'Installing': '安装',
    'Implementing': '实施',
    'Deploying': '部署',
    'Launching': '启动',
    'Initiating': '启动',
    'Starting': '开始',
    'Beginning': '开始',
    'Commencing': '开始',
    'Embarking': '开始',
    'Proceeding': '继续',
    'Continuing': '继续',
    'Advancing': '前进',
    'Progressing': '进展',
    'Moving forward': '前进',
    'Going forward': '前进',
    'Looking ahead': '展望',
    'Planning': '规划',
    'Anticipating': '预期',
    'Expecting': '期望',
    'Hoping': '希望',
    'Wishing': '希望',
    'Wanting': '想要',
    'Desiring': '渴望',
    'Craving': '渴望',
    'Yearning': '渴望',
    'Longing': '渴望',
    'Aspiring': '渴望',
    'Seeking': '寻求',
    'Pursuing': '追求',
    'Chasing': '追逐',
    'Following': '跟随',
    'Tracking': '跟踪',
    'Tracing': '追踪',
    'Monitoring': '监控',
    'Observing': '观察',
    'Watching': '观看',
    'Supervising': '监督',
    'Overseeing': '监督',
    'Managing': '管理',
    'Controlling': '控制',
    'Regulating': '监管',
    'Governing': '治理',
    'Ruling': '统治',
    'Commanding': '命令',
    'Directing': '指导',
    'Instructing': '指示',
    'Teaching': '教学',
    'Educating': '教育',
    'Training': '培训',
    'Coaching': '辅导',
    'Mentoring': '指导',
    'Advising': '建议',
    'Counseling': '咨询',
    'Consulting': '咨询',
    'Guiding': '指导',
    'Leading': '领导',
    'Inspiring': '激励',
    'Influencing': '影响',
    'Persuading': '说服',
    'Convincing': '使相信',
    'Encouraging': '鼓励',
    'Motivating': '激励',
    'Stimulating': '刺激',
    'Activating': '激活',
    'Triggering': '触发',
    'Initiating': '启动',
    'Launching': '启动',
    'Starting': '开始',
    'Beginning': '开始',
    'Creating': '创建',
    'Generating': '生成',
    'Producing': '生产',
    'Making': '制造',
    'Building': '构建',
    'Constructing': '构建',
    'Developing': '开发',
    'Designing': '设计',
    'Planning': '规划',
    'Organizing': '组织',
    'Arranging': '安排',
    'Preparing': '准备',
    'Setting up': '设置',
    'Establishing': '建立',
    'Founding': '建立',
    'Creating': '创建',
    'Forming': '形成',
    'Making': '制造',
    'Building': '构建',
    'Developing': '开发',
    'Growing': '增长',
    'Expanding': '扩展',
    'Extending': '扩展',
    'Broadening': '拓宽',
    'Widening': '扩大',
    'Enlarging': '扩大',
    'Increasing': '增加',
    'Raising': '提高',
    'Enhancing': '增强',
    'Improving': '改进',
    'Bettering': '改善',
    'Upgrading': '升级',
    'Advancing': '前进',
    'Progressing': '进展',
    'Moving': '移动',
    'Shifting': '转移',
    'Changing': '改变',
    'Transforming': '转型',
    'Converting': '转换',
    'Adapting': '适应',
    'Adjusting': '调整',
    'Modifying': '修改',
    'Altering': '更改',
    'Revising': '修订',
    'Updating': '更新',
    'Refreshing': '刷新',
    'Renewing': '更新',
    'Restoring': '恢复',
    'Reviving': '复苏',
    'Rejuvenating': '恢复活力',
    'Regenerating': '再生',
    'Reinventing': '重新发明',
    'Innovating': '创新',
    'Pioneering': '开创',
    'Leading': '领导',
    'Trailblazing': '开拓',
    'Breaking new ground': '开辟新天地',
    'Setting trends': '引领趋势',
    'Making history': '创造历史',
    'Creating legacy': '创造遗产',
    'Building future': '建设未来',
    'Shaping tomorrow': '塑造明天',
    'Transforming world': '改变世界',
    'Making difference': '产生影响',
    'Creating impact': '创造影响',
    'Driving change': '推动变革',
    'Leading transformation': '引领转型',
    'Inspiring action': '激励行动',
    'Motivating others': '激励他人',
    'Empowering people': '赋权于人',
    'Enabling success': '赋能成功',
    'Facilitating growth': '促进增长',
    'Supporting development': '支持发展',
    'Promoting progress': '促进进步',
    'Advancing knowledge': '推进知识',
    'Expanding understanding': '扩展理解',
    'Deepening insights': '深化洞察',
    'Broadening perspectives': '拓宽视角',
    'Enhancing awareness': '增强意识',
    'Increasing consciousness': '提升意识',
    'Elevating thinking': '提升思维',
    'Raising standards': '提高标准',
    'Setting benchmarks': '设定基准',
    'Establishing excellence': '建立卓越',
    'Defining quality': '定义质量',
    'Creating value': '创造价值',
    'Delivering results': '交付结果',
    'Achieving goals': '实现目标',
    'Reaching objectives': '达成目标',
    'Meeting targets': '达成目标',
    'Fulfilling potential': '发挥潜力',
    'Realizing dreams': '实现梦想',
    'Making aspirations': '抱负',
    'Creating opportunities': '创造机会',
    'Opening possibilities': '打开可能性',
    'Exploring potential': '探索潜力',
    'Discovering talents': '发现才能',
    'Uncovering abilities': '发现能力',
    'Revealing capabilities': '揭示能力',
    'Demonstrating skills': '展示技能',
    'Showcasing expertise': '展示专业知识',
    'Highlighting strengths': '突出优势',
    'Emphasizing qualities': '强调品质',
    'Focusing on excellence': '专注卓越',
    'Striving for perfection': '追求完美',
    'Pursuing mastery': '追求精通',
    'Seeking improvement': '寻求改进',
    'Working towards advancement': '努力前进',
    'Moving forward': '前进',
    'Progressing steadily': '稳步进展',
    'Growing continuously': '持续增长',
    'Evolving constantly': '不断演进',
    'Developing consistently': '持续发展',
    'Improving relentlessly': '不懈改进',
    'Enhancing significantly': '显著增强',
    'Optimizing effectively': '有效优化',
    'Perfecting diligently': '勤奋完善',
    'Mastering gradually': '逐步精通',
    'Learning continuously': '持续学习',
    'Adapting quickly': '快速适应',
    'Responding promptly': '迅速响应',
    'Acting decisively': '果断行动',
    'Leading confidently': '自信领导',
    'Inspiring daily': '每日激励',
    'Motivating consistently': '持续激励',
    'Encouraging genuinely': '真诚鼓励',
    'Supporting faithfully': '忠实支持',
    'Helping willingly': '乐意帮助',
    'Serving selflessly': '无私服务',
    'Contributing meaningfully': '有意义贡献',
    'Participating actively': '积极参与',
    'Engaging enthusiastically': '热情参与',
    'Collaborating effectively': '有效协作',
    'Cooperating harmoniously': '和谐合作',
    'Communicating clearly': '清晰沟通',
    'Connecting authentically': '真诚连接',
    'Building relationships': '建立关系',
    'Creating community': '创建社区',
    'Fostering belonging': '培养归属感',
    'Promoting inclusion': '促进包容',
    'Celebrating diversity': '庆祝多样性',
    'Embracing differences': '拥抱差异',
    'Valuing uniqueness': '重视独特性',
    'Respecting individuality': '尊重个性',
    'Honoring identity': '尊重身份',
    'Protecting dignity': '保护尊严',
    'Upholding rights': '维护权利',
    'Defending freedom': '捍卫自由',
    'Championing justice': '倡导正义',
    'Promoting equality': '促进平等',
    'Advocating fairness': '倡导公平',
    'Supporting empowerment': '支持赋权',
    'Enabling participation': '促进参与',
    'Facilitating engagement': '促进参与',
    'Encouraging expression': '鼓励表达',
    'Inspiring creativity': '激发创造力',
    'Stimulating innovation': '刺激创新',
    'Fostering imagination': '培养想象力',
    'Nurturing talent': '培养才能',
    'Developing potential': '开发潜力',
    'Cultivating skills': '培养技能',
    'Building capabilities': '建设能力',
    'Strengthening competencies': '加强能力',
    'Enhancing expertise': '增强专业知识',
    'Deepening knowledge': '深化知识',
    'Broadening understanding': '扩展理解',
    'Expanding awareness': '扩展意识',
    'Increasing consciousness': '提高意识',
    'Elevating perspectives': '提升视角',
    'Transforming mindsets': '转变思维',
    'Shaping attitudes': '塑造态度',
    'Influencing behaviors': '影响行为',
    'Changing habits': '改变习惯',
    'Improving practices': '改进实践',
    'Optimizing processes': '优化流程',
    'Streamlining operations': '简化运营',
    'Enhancing efficiency': '提高效率',
    'Boosting productivity': '提升生产力',
    'Maximizing performance': '最大化性能',
    'Achieving excellence': '实现卓越',
    'Delivering quality': '交付质量',
    'Ensuring satisfaction': '确保满意',
    'Creating value': '创造价值',
    'Generating impact': '产生影响力',
    'Making difference': '产生影响',
    'Leaving legacy': '留下遗产',
    'Creating future': '创造未来',
    'Building tomorrow': '建设明天',
    'Shaping destiny': '塑造命运',
    'Defining success': '定义成功',
    'Achieving dreams': '实现梦想',
    'Realizing potential': '实现潜力',
    'Fulfilling purpose': '实现目标',
    'Living meaningfully': '有意义地生活',
    'Making impact': '产生影响',
    'Creating change': '创造变化',
    'Driving progress': '推动进步',
    'Leading transformation': '引领转型',
    'Inspiring innovation': '激励创新',
    'Empowering success': '赋能成功',
    'Enabling achievement': '赋能成就',
    'Supporting growth': '支持增长',
    'Promoting development': '促进发展',
    'Advancing excellence': '推进卓越',
    'Building capacity': '建设能力',
    'Strengthening foundations': '加强基础',
    'Creating opportunities': '创造机会',
    'Opening doors': '打开机会之门',
    'Expanding horizons': '拓展视野',
    'Broadening perspectives': '拓宽视角',
    'Deepening understanding': '深化理解',
    'Enhancing knowledge': '增强知识',
    'Improving skills': '提高技能',
    'Developing talents': '培养才能',
    'Nurturing potential': '培养潜力',
    'Cultivating abilities': '培养能力',
    'Fostering growth': '促进增长',
    'Encouraging progress': '鼓励进步',
    'Supporting advancement': '支持前进',
    'Promoting success': '促进成功',
    'Enabling achievement': '赋能成就',
    'Facilitating development': '促进发展',
    'Building capabilities': '建设能力',
    'Strengthening competencies': '加强能力',
    'Enhancing expertise': '增强专业知识',
    'Creating excellence': '创造卓越',
    'Achieving mastery': '实现精通',
    'Delivering results': '交付结果',
    'Generating value': '创造价值',
    'Making impact': '产生影响',
    'Creating legacy': '创造遗产',
    'Building future': '建设未来',
    'Transforming lives': '改变生活',
    'Inspiring change': '激励变革',
    'Leading innovation': '引领创新',
    'Driving excellence': '推动卓越',
    'Enabling success': '赋能成功',
    'Empowering achievement': '赋能成就',
    'Supporting potential': '支持潜力',
    'Fostering development': '促进发展',
    'Promoting growth': '促进增长',
    'Advancing progress': '推进进步',
    'Building tomorrow': '建设明天',
    'Creating destiny': '创造命运',
    'Shaping future': '塑造未来',
    'Defining excellence': '定义卓越',
    'Achieving success': '实现成功',
    'Realizing dreams': '实现梦想',
    'Fulfilling aspirations': '实现抱负',
    'Living purposefully': '有目的地生活',
    'Making meaning': '创造意义',
    'Creating value': '创造价值',
    'Generating impact': '产生影响力',
    'Leaving mark': '留下印记',
    'Building legacy': '建设遗产',
    'Shaping history': '塑造历史',
    'Making difference': '产生影响',
    'Creating change': '创造变化',
    'Driving transformation': '推动转型',
    'Leading revolution': '领导革命',
    'Inspiring evolution': '激励演进',
    'Enabling progress': '促进进步',
    'Supporting advancement': '支持前进',
    'Promoting innovation': '促进创新',
    'Fostering creativity': '培养创造力',
    'Cultivating imagination': '培养想象力',
    'Nurturing inspiration': '培养灵感',
    'Developing genius': '培养天才',
    'Uncovering potential': '发现潜力',
    'Revealing talent': '发现才能',
    'Discovering abilities': '发现能力',
    'Showcasing skills': '展示技能',
    'Demonstrating expertise': '展示专业知识',
    'Highlighting capabilities': '突出能力',
    'Emphasizing strengths': '强调优势',
    'Focusing on excellence': '专注卓越',
    'Striving for perfection': '追求完美',
    'Pursuing greatness': '追求伟大',
    'Seeking mastery': '寻求精通',
    'Working towards brilliance': '努力追求卓越',
    'Moving forward': '前进',
    'Progressing daily': '每日进步',
    'Growing constantly': '持续增长',
    'Evolving continuously': '不断演进',
    'Developing steadily': '稳步发展',
    'Improving consistently': '持续改进',
    'Enhancing significantly': '显著增强',
    'Optimizing effectively': '有效优化',
    'Perfecting diligently': '勤奋完善',
    'Mastering gradually': '逐步精通',
    'Learning always': '永远学习',
    'Adapting rapidly': '快速适应',
    'Responding immediately': '立即响应',
    'Acting purposefully': '有目的地行动',
    'Leading confidently': '自信领导',
    'Inspiring others': '激励他人',
    'Motivating teams': '激励团队',
    'Empowering individuals': '赋权个人',
    'Enabling organizations': '赋能组织',
    'Transforming communities': '改变社区',
    'Impact society': '影响社会',
    'Change world': '改变世界',
    'Make difference': '产生影响',
    'Create legacy': '创造遗产',
    'Build future': '建设未来',
    'Shape destiny': '塑造命运'
  };

  let translated = title;

  // 应用翻译规则
  for (const [english, chinese] of Object.entries(translations)) {
    const regex = new RegExp(english.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'gi');
    translated = translated.replace(regex, chinese);
  }

  // 如果没有翻译，返回通用翻译
  if (translated === title) {
    if (title.toLowerCase().includes('workflow')) {
      translated = title.replace(/workflow/gi, '工作流');
    } else if (title.toLowerCase().includes('trigger')) {
      translated = title.replace(/trigger/gi, '触发器');
    } else if (title.toLowerCase().includes('automation')) {
      translated = title.replace(/automation/gi, '自动化');
    } else if (title.toLowerCase().includes('agent')) {
      translated = title.replace(/agent/gi, '智能代理');
    } else {
      // 简单的通用翻译
      translated = `${title} 工作流`;
    }
  }

  return translated.trim();
}

function translateDescription(description) {
  let translated = description;

  // 基本翻译规则
  const basicTranslations = {
    'Automated workflow:': '自动化工作流：',
    'Production-ready workflow:': '生产就绪工作流：',
    'This workflow processes data and performs automated tasks.': '此工作流处理数据并执行自动化任务。',
    'This workflow has been optimized for production use with comprehensive error handling, security, and documentation.': '此工作流已针对生产使用进行优化，具有全面的错误处理、安全性和文档。',
    'integrates': '集成',
    'different services': '个不同的服务',
    'nodes': '个节点',
    'follows best practices for error handling and security': '遵循错误处理和安全最佳实践',
    'contains': '包含'
  };

  for (const [english, chinese] of Object.entries(basicTranslations)) {
    const regex = new RegExp(english.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'gi');
    translated = translated.replace(regex, chinese);
  }

  return translated.trim();
}

// 从文件名提取工作流ID
function getWorkflowId(filePath) {
  const filename = path.basename(filePath, '.json');
  return filename;
}

// 主函数
function main() {
  try {
    console.log('🚀 开始自动化工作流汉化...');

    // 读取报告文件
    const reportData = JSON.parse(fs.readFileSync(REPORT_JSON_PATH, 'utf8'));
    const workflowsToTranslate = reportData.needLocalizationList;

    console.log(`📊 总共需要汉化的工作流: ${workflowsToTranslate.length}`);

    // 读取现有翻译文件
    const translationData = JSON.parse(fs.readFileSync(TRANSLATION_FILE_PATH, 'utf8'));

    // 统计已有翻译
    const existingTranslations = Object.keys(translationData.workflows || {});
    console.log(`✅ 已有翻译的工作流: ${existingTranslations.length}`);

    // 找出未翻译的工作流
    const untranslatedWorkflows = workflowsToTranslate.filter(wf => {
      const workflowId = getWorkflowId(wf.file);
      return !existingTranslations.includes(workflowId);
    });

    console.log(`📝 待翻译的工作流: ${untranslatedWorkflows.length}`);

    if (untranslatedWorkflows.length === 0) {
      console.log('🎉 所有工作流都已完成翻译！');
      return;
    }

    // 分批处理
    const batches = [];
    for (let i = 0; i < untranslatedWorkflows.length; i += BATCH_SIZE) {
      batches.push(untranslatedWorkflows.slice(i, i + BATCH_SIZE));
    }

    console.log(`📦 将分 ${batches.length} 批处理，每批 ${BATCH_SIZE} 个工作流`);

    // 处理每批翻译
    let totalProcessed = 0;
    for (let batchIndex = 0; batchIndex < batches.length; batchIndex++) {
      const batch = batches[batchIndex];
      console.log(`\n🔄 处理第 ${batchIndex + 1}/${batches.length} 批...`);

      // 初始化 workflows 对象（如果不存在）
      if (!translationData.workflows) {
        translationData.workflows = {};
      }

      // 添加这批翻译
      for (const workflow of batch) {
        const workflowId = getWorkflowId(workflow.file);

        translationData.workflows[workflowId] = {
          title: translateTitle(workflow.name),
          description: translateDescription(workflow.description)
        };

        totalProcessed++;

        if (totalProcessed % 50 === 0) {
          console.log(`  ✅ 已处理 ${totalProcessed} 个工作流`);
        }
      }

      // 每批处理后保存文件
      fs.writeFileSync(TRANSLATION_FILE_PATH, JSON.stringify(translationData, null, 2), 'utf8');
      console.log(`  💾 第 ${batchIndex + 1} 批翻译已保存 (${batch.length} 个工作流)`);
    }

    console.log(`\n🎉 翻译完成！`);
    console.log(`📈 总计处理: ${totalProcessed} 个工作流`);
    console.log(`📖 翻译文件: ${TRANSLATION_FILE_PATH}`);

    // 验证结果
    const finalTranslationData = JSON.parse(fs.readFileSync(TRANSLATION_FILE_PATH, 'utf8'));
    const finalTranslationCount = Object.keys(finalTranslationData.workflows || {});
    console.log(`✨ 最终翻译数量: ${finalTranslationCount.length}`);

  } catch (error) {
    console.error('❌ 翻译过程中出现错误:', error.message);
    process.exit(1);
  }
}

// 运行脚本
if (require.main === module) {
  main();
}

module.exports = {
  translateTitle,
  translateDescription,
  getWorkflowId,
  main
};